select * from outwards_policy where 
sequence_number=179757

SELECT          
            ORA_HASH(         
                 IP.SEQUENCE_NUMBER ||         
                 OC.CLAIM_NUMBER ||         
                 OXCT.BOOKED_TRANS_NO_INWARDS ||         
                 OXCT.BOOKED_TRANS_NO         
               ) AS ROW_KEY_ID,         
            IP.SEQUENCE_NUMBER IW_SEQUENCE_NUMBER,            
            IP.CONTRACT_NUMBER IW_CONTRACT_NUMBER,            
            IP.UNDERWRITING_YEAR IW_UNDERWRITING_YEAR,            
            OP.SEQUENCE_NUMBER OP_SEQUENCE_NUMBER,            
            OP.CONTRACT_NUMBER OP_CONTRACT_NUMBER,            
            OP.UNDERWRITING_YEAR OP_UNDERWRITING_YEAR,            
            OC.CLAIM_NUMBER IW_CLAIM_NUMBER,            
            OXCT.BOOKED_TRANS_NO_INWARDS IW_BOOKED_TRANS_NO,            
            OXCT.BOOKED_TRANS_NO OW_BOOKED_TRANS_NO,            
            OC.ACCUMULATION_CODE OW_ACCUMULATION_CODE             
        FROM OUTWARDS_POLICY OP,            
             INWARDS_POLICY IP,            
             OUTWARDS_XL_CLAIM_TRAN OXCT,            
             OUTWARDS_CLAIM OC            
        WHERE OXCT.INWARDS_POLICY_SEQUENCE_NO is not null        
        AND OXCT.BOOKED_TRANS_NO_INWARDS IS NOT NULL        
        AND IP.SEQUENCE_NUMBER = OXCT.INWARDS_POLICY_SEQUENCE_NO            
        AND OP.SEQUENCE_NUMBER = 179757      
        AND OC.OUTWARDS_POLICY_SEQUENCE_NO = OP.SEQUENCE_NUMBER            
        AND OXCT.OUTWARDS_POLICY_SEQUENCE_NO = OP.SEQUENCE_NUMBER

SELECT * FROM INWARDS_XL_CLAIM_TRAN  WHERE CLAIM_NUMBER=191179;
    SELECT * FROM INWARDS_PRO_RATA_CLAIM_TRAN WHERE CLAIM_NUMBER=191179;  SELECT * FROM INWARDS_CLAIM  WHERE CLAIM_NUMBER=191179;
